services:
  - type: web
    name: mp3-music-player
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
